language: csharp
solution: AzureWebJobsCertificateUpdater.sln
mono: none
dist: xenial
dotnet: 2.2
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet restore
  - dotnet build
  - dotnet publish -c Release
